Compatibility 232 (#143)
open-policy-agent/opa-idea-plugin pull request #144
Opened 2023-03-31 08:46 UTC by SilverSilence

* Update Kotlin JVM Version
* Update Intellij Plugin Version
* Update Supported-Until Version

# Description
 
 

Fixes #

# Special notes for your reviewer

2023-03-31 13:12 UTC, vgramer requested changes

2023-03-31 13:12 UTC, vgramer commented on build.gradle.kts
> +    id("org.jetbrains.intellij") version "1.13.2"
```suggestion
    id("org.jetbrains.intellij") version "1.13.3"
```
we can bump to the very last version  ;) (released 2 day ago )

2023-03-31 13:12 UTC, vgramer commented on gradle.properties
> +psiViewerPluginVersion=231-SNAPSHOT
The plugin should be tested on the oldest version supported
```
ideaVersion=IC-2022.2
pycharmCommunityVersion=PC-2022.2
psiViewerPluginVersion=222-SNAPSHOT
```

2023-03-31 13:12 UTC, vgramer commented on gradle.properties
>  sinceBuild=221
We support only the last 3 major releases
```suggestion
sinceBuild=222
```

2023-04-01 07:35 UTC, SilverSilence commented on gradle.properties
> +psiViewerPluginVersion=231-SNAPSHOT
It seems that `IC-2022.2` is not compatible with `PsiViewerPluginVersion=231-SNAPSHOT`.

2023-04-02 08:20 UTC, vgramer commented on gradle.properties
> +psiViewerPluginVersion=231-SNAPSHOT
the versions should be bumped as follow:
```
ideaVersion=IC-2022.2
pycharmCommunityVersion=PC-2022.2
psiViewerPluginVersion=222-SNAPSHOT
```

idea and pycharm are bumped to `2022.2` and psiViewerPluginVersion is bumped to` 222-SNAPSHOT`.

by the way, the PsiViewerPluginVersion is the version of psi viewer plugin to install in the testing ide. So it should match the version of the testing ide.

2023-04-03 06:31 UTC, SilverSilence commented on gradle.properties
> +psiViewerPluginVersion=231-SNAPSHOT
With your configurations, I get this error:

`Plugin 'PsiViewer:222-SNAPSHOT' is not compatible to: IC-221.5080.210`

2023-04-03 12:08 UTC, SilverSilence commented on gradle.properties
> +psiViewerPluginVersion=231-SNAPSHOT
Seems I copied it wrong, my bad.. Works now. I'm sorry that this took several iterations.

2023-04-03 12:40 UTC, vgramer commented on gradle.properties
> +psiViewerPluginVersion=231-SNAPSHOT
np :)

2023-04-04 10:41 UTC, SilverSilence commented
I don't know how to resolve this error `Must not use `executable` property on `Test` together with `javaLauncher` property` 😔

2023-04-04 10:49 UTC, vgramer commented
I have an idea of what it. I need to do some testing. I will let you know

2023-04-05 12:14 UTC, vgramer commented
the version of gradle nee

> I don't know how to resolve this error `Must not use "executable" property on "Test" together with "javaLauncher" property` 😔

To fix it, I had to bump the version of Gradle. I also took the opportunity to bump the Kotlin jvm  version and JDK used in the Github action

2023-04-05 12:14 UTC, vgramer approved these changes

2023-04-05 12:18 UTC, merged

2023-04-05 12:19 UTC, vgramer commented
@SilverSilence  Thanks for contributing to the project :)